### ISSUE TITLE
Failed to compile in Debian 8.5

### ISSUE THREAD

**Issue by brunovila** [iTALC/italc#39]
I tried to compile Italc 3.0 in Debian 8.5 and I have this error

_> [ 26%] Building CXX object lib/CMakeFiles/ItalcCore.dir/src/ItalcVncConnection.o
> /home/ladmin/Documentos/italc-3.0.0/lib/src/ItalcVncConnection.cpp: In member function ‘void ItalcVncConnection::stop(bool)’:
> /home/ladmin/Documentos/italc-3.0.0/lib/src/ItalcVncConnection.cpp:385:86: error: no matching function for call to ‘QTimer::singleShot(ItalcVncConnection::<anonymous enum>, ItalcVncConnection*, void (QThread::*)())’
>    QTimer::singleShot( ThreadTerminationTimeout, this, &ItalcVncConnection::terminate );
>                                                                                       ^
> /home/ladmin/Documentos/italc-3.0.0/lib/src/ItalcVncConnection.cpp:385:86: note: candidates are:
> In file included from /usr/include/x86_64-linux-gnu/qt5/QtCore/QTimer:1:0,
>                  from /home/ladmin/Documentos/italc-3.0.0/lib/src/ItalcVncConnection.cpp:39:
> /usr/include/x86_64-linux-gnu/qt5/QtCore/qtimer.h:81:17: note: static void QTimer::singleShot(int, const QObject*, const char*)
>      static void singleShot(int msec, const QObject *receiver, const char *member);
>                  ^
> /usr/include/x86_64-linux-gnu/qt5/QtCore/qtimer.h:81:17: note:   no known conversion for argument 3 from ‘void (QThread::*)()’ to ‘const char*’
> /usr/include/x86_64-linux-gnu/qt5/QtCore/qtimer.h:82:17: note: static void QTimer::singleShot(int, Qt::TimerType, const QObject*, const char*)
>      static void singleShot(int msec, Qt::TimerType timerType, const QObject *receiver, const char *member);
>                  ^
> /usr/include/x86_64-linux-gnu/qt5/QtCore/qtimer.h:82:17: note:   candidate expects 4 arguments, 3 provided
> lib/CMakeFiles/ItalcCore.dir/build.make:668: recipe for target 'lib/CMakeFiles/ItalcCore.dir/src/ItalcVncConnection.o' failed
> make[2]: *** [lib/CMakeFiles/ItalcCore.dir/src/ItalcVncConnection.o] Error 1
> CMakeFiles/Makefile2:2070: recipe for target 'lib/CMakeFiles/ItalcCore.dir/all' failed
> make[1]: *** [lib/CMakeFiles/ItalcCore.dir/all] Error 2
> Makefile:137: recipe for target 'all' failed
> make: *** [all] Error 2_
