### PR TITLE
QtSlaveLauncher: fix build for Qt < 5.7.0 (#92)

### LINKED ISSUE #92: Failed to compile in openSUSE 42.2
I tried to compile iTALC 3.0.3 on openSUSE 42.2, and I got the following error:

`
_### _[ 28%] Building CXX object lib/CMakeFiles/ItalcCore.dir/src/Ipc/QtSlaveLauncher.o
[ 28%] Building CXX object lib/CMakeFiles/ItalcCore.dir/src/Ipc/Slave.o
[ 28%] Building CXX object lib/CMakeFiles/ItalcCore.dir/src/Ipc/SlaveLauncher.o
/home/user/bin/Source_code_installers/iTALC/italc/lib/src/Ipc/QtSlaveLauncher.cpp: In member function ‘virtual void Ipc::QtSlaveLauncher::start(const QStringList&)’:
/home/user/bin/Source_code_installers/iTALC/italc/lib/src/Ipc/QtSlaveLauncher.cpp:70:42: error: no matching function for call to ‘Ipc::QtSlaveLauncher::connect(QPointer<QProcess>&, void (QProcess::*)(int, QProcess::ExitStatus), QPointer<QProcess>&, void (QObject::*)())’
        m_process, &QProcess::deleteLater );
                                          ^
/home/user/bin/Source_code_installers/iTALC/italc/lib/src/Ipc/QtSlaveLauncher.cpp:70:42: note: candidates are:
In file included from /usr/include/qt5/QtCore/qcoreapplication.h:40:0,
                 from /usr/include/qt5/QtCore/QCoreApplication:1,
                 from /home/user/bin/Source_code_installers/iTALC/italc/lib/src/Ipc/QtSlaveLauncher.cpp:27:
/usr/include/qt5/QtCore/qobject.h:196:36: note: static QMetaObject::Connection QObject::connect(const QObject*, const char*, const QObject*, const char*, Qt::ConnectionType)
     static QMetaObject::Connection connect(const QObject *sender, const char *signal,

lib/CMakeFiles/ItalcCore.dir/build.make:729: recipe for target 'lib/CMakeFiles/ItalcCore.dir/src/Ipc/QtSlaveLauncher.o' failed
make[2]: *** [lib/CMakeFiles/ItalcCore.dir/src/Ipc/QtSlaveLauncher.o] Error 1
make[2]: *** Waiting for unfinished jobs....
CMakeFiles/Makefile2:2309: recipe for target 'lib/CMakeFiles/ItalcCore.dir/all' failed
make[1]: *** [lib/CMakeFiles/ItalcCore.dir/all] Error 2
Makefile:149: recipe for target 'all' failed
make: *** [all] Error 2
user@linux-home-pc:~/bin/Source_code_installers/iTALC/italc>__ 
`

### PR DESCRIPTION
**Pull request by lbssousa**
This patch fixes builds for Qt 5.6.x and lower, making it suitable for some LTS Linux distros (Ubuntu 14.04, openSUSE Leap 42.1 & 42.2, etc.). Closes #92.

### CODE REVIEW

**Comment by tobydox** [comment]
Thanks for the patch!
